// This file was generated by RedwoodJS
import * as Cell from './EditProjectDataCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditProjectDataById, EditProjectDataByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditProjectDataCell'

type CellInputs = CellProps<SuccessType, EditProjectDataById, typeof Cell, EditProjectDataByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
