// This file was generated by RedwoodJS
import * as Cell from './EditServiceAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminEditServiceById, AdminEditServiceByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditServiceAdminCell'

type CellInputs = CellProps<SuccessType, AdminEditServiceById, typeof Cell, AdminEditServiceByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
