// This file was generated by RedwoodJS
import * as Cell from './ContactSubmissionAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { ContactSubmissionAdminQuery, ContactSubmissionAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ContactSubmissionAdminCell'

type CellInputs = CellProps<SuccessType, ContactSubmissionAdminQuery, typeof Cell, ContactSubmissionAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
