// This file was generated by RedwoodJS
import * as Cell from './ResearchArticleCell'
import type { CellProps } from '@redwoodjs/web'
import type { ResearchArticleBySlug, ResearchArticleBySlugVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ResearchArticleCell'

type CellInputs = CellProps<SuccessType, ResearchArticleBySlug, typeof Cell, ResearchArticleBySlugVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
