// This file was generated by RedwoodJS
import * as Cell from './ActiveServicesCell'
import type { CellProps } from '@redwoodjs/web'
import type { ActiveServicesQuery, ActiveServicesQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ActiveServicesCell'

type CellInputs = CellProps<SuccessType, ActiveServicesQuery, typeof Cell, ActiveServicesQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
