// This file was generated by RedwoodJS
import * as Cell from './TeamMembersCell'
import type { CellProps } from '@redwoodjs/web'
import type { TeamMembersPublicQuery, TeamMembersPublicQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './TeamMembersCell'

type CellInputs = CellProps<SuccessType, TeamMembersPublicQuery, typeof Cell, TeamMembersPublicQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
