// This file was generated by RedwoodJS
import * as Cell from './NicolaPostsCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindNicolaPosts, FindNicolaPostsVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './NicolaPostsCell'

type CellInputs = CellProps<SuccessType, FindNicolaPosts, typeof Cell, FindNicolaPostsVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
