// This file was generated by RedwoodJS
import * as Cell from './EditFaqAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminEditFaq, AdminEditFaqVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditFaqAdminCell'

type CellInputs = CellProps<SuccessType, AdminEditFaq, typeof Cell, AdminEditFaqVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
