// This file was generated by RedwoodJS
import * as Cell from './EditPricingTierAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditPricingTierAdminQuery, EditPricingTierAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditPricingTierAdminCell'

type CellInputs = CellProps<SuccessType, EditPricingTierAdminQuery, typeof Cell, EditPricingTierAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
