// This file was generated by RedwoodJS
import * as Cell from './SiteSettingsAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { SiteSettingsAdminQuery, SiteSettingsAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './SiteSettingsAdminCell'

type CellInputs = CellProps<SuccessType, SiteSettingsAdminQuery, typeof Cell, SiteSettingsAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
