// This file was generated by RedwoodJS
import * as Cell from './EditTestimonialAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminEditTestimonial, AdminEditTestimonialVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditTestimonialAdminCell'

type CellInputs = CellProps<SuccessType, AdminEditTestimonial, typeof Cell, AdminEditTestimonialVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
