// This file was generated by RedwoodJS
import * as Cell from './ServiceBySlugCell'
import type { CellProps } from '@redwoodjs/web'
import type { ServiceBySlugQuery, ServiceBySlugQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ServiceBySlugCell'

type CellInputs = CellProps<SuccessType, ServiceBySlugQuery, typeof Cell, ServiceBySlugQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
