// This file was generated by RedwoodJS
import * as Cell from './NicolasArticlesCell'
import type { CellProps } from '@redwoodjs/web'
import type { NicolasArticlesQuery, NicolasArticlesQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './NicolasArticlesCell'

type CellInputs = CellProps<SuccessType, NicolasArticlesQuery, typeof Cell, NicolasArticlesQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
