// This file was generated by RedwoodJS
import * as Cell from './ServiceAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminServiceById, AdminServiceByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ServiceAdminCell'

type CellInputs = CellProps<SuccessType, AdminServiceById, typeof Cell, AdminServiceByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
