// This file was generated by RedwoodJS
import * as Cell from './TestimonialsAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminTestimonialsList, AdminTestimonialsListVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './TestimonialsAdminCell'

type CellInputs = CellProps<SuccessType, AdminTestimonialsList, typeof Cell, AdminTestimonialsListVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
