// This file was generated by RedwoodJS
import * as Cell from './RelatedArticlesCell'
import type { CellProps } from '@redwoodjs/web'
import type { RecentPostsQuery, RecentPostsQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './RelatedArticlesCell'

type CellInputs = CellProps<SuccessType, RecentPostsQuery, typeof Cell, RecentPostsQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
