// This file was generated by RedwoodJS
import * as Cell from './EditNicolaPostCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditNicolaPostById, EditNicolaPostByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditNicolaPostCell'

type CellInputs = CellProps<SuccessType, EditNicolaPostById, typeof Cell, EditNicolaPostByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
