// This file was generated by RedwoodJS
import * as Cell from './FaqsAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminFaqsList, AdminFaqsListVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './FaqsAdminCell'

type CellInputs = CellProps<SuccessType, AdminFaqsList, typeof Cell, AdminFaqsListVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
