// This file was generated by RedwoodJS
import * as Cell from './ProjectCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindProjectDatasForProjects, FindProjectDatasForProjectsVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ProjectCell'

type CellInputs = CellProps<SuccessType, FindProjectDatasForProjects, typeof Cell, FindProjectDatasForProjectsVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
