// This file was generated by RedwoodJS
import * as Cell from './EditResearchArticleAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditResearchArticleById, EditResearchArticleByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditResearchArticleAdminCell'

type CellInputs = CellProps<SuccessType, EditResearchArticleById, typeof Cell, EditResearchArticleByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
