// This file was generated by RedwoodJS
import * as Cell from './ProjectDatasCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindProjectDatasList, FindProjectDatasListVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ProjectDatasCell'

type CellInputs = CellProps<SuccessType, FindProjectDatasList, typeof Cell, FindProjectDatasListVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
