// This file was generated by RedwoodJS
import * as Cell from './EditTeamMemberAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminEditTeamMember, AdminEditTeamMemberVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditTeamMemberAdminCell'

type CellInputs = CellProps<SuccessType, AdminEditTeamMember, typeof Cell, AdminEditTeamMemberVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
