// This file was generated by RedwoodJS
import * as Cell from './ClientLogoAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { ClientLogoAdminQuery, ClientLogoAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ClientLogoAdminCell'

type CellInputs = CellProps<SuccessType, ClientLogoAdminQuery, typeof Cell, ClientLogoAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
