// This file was generated by RedwoodJS
import * as Cell from './ResearchArticlesCell'
import type { CellProps } from '@redwoodjs/web'
import type { ResearchArticlesPublic, ResearchArticlesPublicVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ResearchArticlesCell'

type CellInputs = CellProps<SuccessType, ResearchArticlesPublic, typeof Cell, ResearchArticlesPublicVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
