// This file was generated by RedwoodJS
import * as Cell from './TechnologiesAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminTechnologiesList, AdminTechnologiesListVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './TechnologiesAdminCell'

type CellInputs = CellProps<SuccessType, AdminTechnologiesList, typeof Cell, AdminTechnologiesListVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
