// This file was generated by RedwoodJS
import * as Cell from './ServicesAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminServicesList, AdminServicesListVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ServicesAdminCell'

type CellInputs = CellProps<SuccessType, AdminServicesList, typeof Cell, AdminServicesListVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
