// This file was generated by RedwoodJS
import * as Cell from './LegalPageAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { LegalPageAdminQuery, LegalPageAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './LegalPageAdminCell'

type CellInputs = CellProps<SuccessType, LegalPageAdminQuery, typeof Cell, LegalPageAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
