// This file was generated by RedwoodJS
import * as Cell from './ProcessStepsAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { ProcessStepsAdminQuery, ProcessStepsAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ProcessStepsAdminCell'

type CellInputs = CellProps<SuccessType, ProcessStepsAdminQuery, typeof Cell, ProcessStepsAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
