// This file was generated by RedwoodJS
import * as Cell from './PricingTiersAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { PricingTiersAdminQuery, PricingTiersAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './PricingTiersAdminCell'

type CellInputs = CellProps<SuccessType, PricingTiersAdminQuery, typeof Cell, PricingTiersAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
