// This file was generated by RedwoodJS
import * as Cell from './LegalPageBySlugCell'
import type { CellProps } from '@redwoodjs/web'
import type { LegalPageBySlugQuery, LegalPageBySlugQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './LegalPageBySlugCell'

type CellInputs = CellProps<SuccessType, LegalPageBySlugQuery, typeof Cell, LegalPageBySlugQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
