// This file was generated by RedwoodJS
import * as Cell from './FaqsCell'
import type { CellProps } from '@redwoodjs/web'
import type { FaqsPublicQuery, FaqsPublicQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './FaqsCell'

type CellInputs = CellProps<SuccessType, FaqsPublicQuery, typeof Cell, FaqsPublicQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
