// This file was generated by RedwoodJS
import * as Cell from './NewsletterSubscribersAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { NewsletterSubscribersAdminQuery, NewsletterSubscribersAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './NewsletterSubscribersAdminCell'

type CellInputs = CellProps<SuccessType, NewsletterSubscribersAdminQuery, typeof Cell, NewsletterSubscribersAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
