// This file was generated by RedwoodJS
import * as Cell from './LegalPagesAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { LegalPagesAdminQuery, LegalPagesAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './LegalPagesAdminCell'

type CellInputs = CellProps<SuccessType, LegalPagesAdminQuery, typeof Cell, LegalPagesAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
