// This file was generated by RedwoodJS
import * as Cell from './NicolaPostCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindNicolaPostById, FindNicolaPostByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './NicolaPostCell'

type CellInputs = CellProps<SuccessType, FindNicolaPostById, typeof Cell, FindNicolaPostByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
