// This file was generated by RedwoodJS
import * as Cell from './RelatedResearchArticlesCell'
import type { CellProps } from '@redwoodjs/web'
import type { RelatedResearchArticles, RelatedResearchArticlesVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './RelatedResearchArticlesCell'

type CellInputs = CellProps<SuccessType, RelatedResearchArticles, typeof Cell, RelatedResearchArticlesVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
