// This file was generated by RedwoodJS
import * as Cell from './TestimonialAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminTestimonialDetail, AdminTestimonialDetailVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './TestimonialAdminCell'

type CellInputs = CellProps<SuccessType, AdminTestimonialDetail, typeof Cell, AdminTestimonialDetailVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
