// This file was generated by RedwoodJS
import * as Cell from './TeamMembersAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminTeamMembersList, AdminTeamMembersListVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './TeamMembersAdminCell'

type CellInputs = CellProps<SuccessType, AdminTeamMembersList, typeof Cell, AdminTeamMembersListVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
