// This file was generated by RedwoodJS
import * as Cell from './ProjectCell'
import type { CellProps } from '@redwoodjs/web'
import type { ProjectQuery, ProjectQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ProjectCell'

type CellInputs = CellProps<SuccessType, ProjectQuery, typeof Cell, ProjectQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
