// This file was generated by RedwoodJS
import * as Cell from './PricingTierAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { PricingTierAdminQuery, PricingTierAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './PricingTierAdminCell'

type CellInputs = CellProps<SuccessType, PricingTierAdminQuery, typeof Cell, PricingTierAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
