// This file was generated by RedwoodJS
import * as Cell from './FaqAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminFaqDetail, AdminFaqDetailVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './FaqAdminCell'

type CellInputs = CellProps<SuccessType, AdminFaqDetail, typeof Cell, AdminFaqDetailVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
