// This file was generated by RedwoodJS
import * as Cell from './TechnologyAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminTechnologyById, AdminTechnologyByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './TechnologyAdminCell'

type CellInputs = CellProps<SuccessType, AdminTechnologyById, typeof Cell, AdminTechnologyByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
