// This file was generated by RedwoodJS
import * as Cell from './ClientLogosAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { ClientLogosAdminQuery, ClientLogosAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ClientLogosAdminCell'

type CellInputs = CellProps<SuccessType, ClientLogosAdminQuery, typeof Cell, ClientLogosAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
