// This file was generated by RedwoodJS
import * as Cell from './ResearchArticleDraftCell'
import type { CellProps } from '@redwoodjs/web'
import type { ResearchArticleDraftBySlug, ResearchArticleDraftBySlugVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ResearchArticleDraftCell'

type CellInputs = CellProps<SuccessType, ResearchArticleDraftBySlug, typeof Cell, ResearchArticleDraftBySlugVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
