// This file was generated by RedwoodJS
import * as Cell from './ArticleSingleNicolaCell'
import type { CellProps } from '@redwoodjs/web'
import type { ArticleQueryNicola, ArticleQueryNicolaVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ArticleSingleNicolaCell'

type CellInputs = CellProps<SuccessType, ArticleQueryNicola, typeof Cell, ArticleQueryNicolaVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
