// This file was generated by RedwoodJS
import * as Cell from './EditProjectCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditProjectById, EditProjectByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditProjectCell'

type CellInputs = CellProps<SuccessType, EditProjectById, typeof Cell, EditProjectByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
