// This file was generated by RedwoodJS
import * as Cell from './PricingTiersCell'
import type { CellProps } from '@redwoodjs/web'
import type { PricingTiersPublicQuery, PricingTiersPublicQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './PricingTiersCell'

type CellInputs = CellProps<SuccessType, PricingTiersPublicQuery, typeof Cell, PricingTiersPublicQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
