// This file was generated by RedwoodJS
import * as Cell from './ResearchArticlesAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminResearchPostsList, AdminResearchPostsListVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ResearchArticlesAdminCell'

type CellInputs = CellProps<SuccessType, AdminResearchPostsList, typeof Cell, AdminResearchPostsListVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
