// This file was generated by RedwoodJS
import * as Cell from './EditProcessStepAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditProcessStepAdminQuery, EditProcessStepAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditProcessStepAdminCell'

type CellInputs = CellProps<SuccessType, EditProcessStepAdminQuery, typeof Cell, EditProcessStepAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
