// This file was generated by RedwoodJS
import * as Cell from './TeamMemberAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminTeamMemberDetail, AdminTeamMemberDetailVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './TeamMemberAdminCell'

type CellInputs = CellProps<SuccessType, AdminTeamMemberDetail, typeof Cell, AdminTeamMemberDetailVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
