// This file was generated by RedwoodJS
import * as Cell from './EditTechnologyAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { AdminEditTechnologyById, AdminEditTechnologyByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditTechnologyAdminCell'

type CellInputs = CellProps<SuccessType, AdminEditTechnologyById, typeof Cell, AdminEditTechnologyByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
