// This file was generated by RedwoodJS
import * as Cell from './ProcessStepsCell'
import type { CellProps } from '@redwoodjs/web'
import type { ProcessStepsPublicQuery, ProcessStepsPublicQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ProcessStepsCell'

type CellInputs = CellProps<SuccessType, ProcessStepsPublicQuery, typeof Cell, ProcessStepsPublicQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
