// This file was generated by RedwoodJS
import * as Cell from './EditPostCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditPostByIdScaffold, EditPostByIdScaffoldVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditPostCell'

type CellInputs = CellProps<SuccessType, EditPostByIdScaffold, typeof Cell, EditPostByIdScaffoldVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
