// This file was generated by RedwoodJS
import * as Cell from './EditLegalPageAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditLegalPageAdminQuery, EditLegalPageAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditLegalPageAdminCell'

type CellInputs = CellProps<SuccessType, EditLegalPageAdminQuery, typeof Cell, EditLegalPageAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
