// This file was generated by RedwoodJS
import * as Cell from './ArticleSingleAaronCell'
import type { CellProps } from '@redwoodjs/web'
import type { ArticleQueryAaron, ArticleQueryAaronVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ArticleSingleAaronCell'

type CellInputs = CellProps<SuccessType, ArticleQueryAaron, typeof Cell, ArticleQueryAaronVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
