// This file was generated by RedwoodJS
import * as Cell from './ProcessStepAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { ProcessStepAdminQuery, ProcessStepAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ProcessStepAdminCell'

type CellInputs = CellProps<SuccessType, ProcessStepAdminQuery, typeof Cell, ProcessStepAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
