// This file was generated by RedwoodJS
import * as Cell from './ContactSubmissionsAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { ContactSubmissionsAdminQuery, ContactSubmissionsAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ContactSubmissionsAdminCell'

type CellInputs = CellProps<SuccessType, ContactSubmissionsAdminQuery, typeof Cell, ContactSubmissionsAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
