// This file was generated by RedwoodJS
import * as Cell from './ProjectsCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindProjects, FindProjectsVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ProjectsCell'

type CellInputs = CellProps<SuccessType, FindProjects, typeof Cell, FindProjectsVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
