// This file was generated by RedwoodJS
import * as Cell from './EditClientLogoAdminCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditClientLogoAdminQuery, EditClientLogoAdminQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditClientLogoAdminCell'

type CellInputs = CellProps<SuccessType, EditClientLogoAdminQuery, typeof Cell, EditClientLogoAdminQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
